In [109]:
import pandas as pd
import numpy as np

In [110]:
# 1 Pandas Series — Marks
marks = pd.Series([78, 85, 92, 67, 88])

print("Complete Series:")
print(marks)

print("\nValues:")
print(marks.values)

print("\nIndex:")
print(marks.index)

print("\nData type:")
print(marks.dtype)

print("\nMean:")
print(marks.mean())

print("\nMaximum:")
print(marks.max())

print("\nMinimum:")
print(marks.min())

Complete Series:
0    78
1    85
2    92
3    67
4    88
dtype: int64

Values:
[78 85 92 67 88]

Index:
RangeIndex(start=0, stop=5, step=1)

Data type:
int64

Mean:
82.0

Maximum:
92

Minimum:
67

In [111]:
# 2. Series with Student Names

marks = pd.Series(
    [85, 78, 92, 74, 88],
    index=["Asha", "Ravi", "Meena", "Kiran", "Arun"]
)

print(marks)

print("\nMarks of Meena:")
print(marks["Meena"])

Asha     85
Ravi     78
Meena    92
Kiran    74
Arun     88
dtype: int64

Marks of Meena:
92

In [112]:
# 3. Create DataFrame
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["CSE", "ECE", "CSE", "ME", "ECE"],
    "Marks": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

print("Complete DataFrame:")
print(df)

print("\nFirst 3 rows:")
print(df.head(3))

print("\nLast 2 rows:")
print(df.tail(2))

Complete DataFrame:
    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

First 3 rows:
    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Last 2 rows:
    Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

In [113]:
print("\nShape:---")
print(df.shape)

print("\nColumn names:")
print(df.columns)

print("\nData types:---\n")
print(df.dtypes)

Shape:---
(5, 4)

Column names:
Index(['Name', 'Age', 'Department', 'Marks'], dtype='str')

Data types:---

Name            str
Age           int64
Department      str
Marks         int64
dtype: object

In [114]:
#4. info(), describe(), Rows and Columns
print("Info:-\n")
df.info()
#print("\n")

print("\nDescribe:-\n")
print(df.describe())

print("\nNumber of rows:-\n")
print(df.shape[0])

print("\nNumber of columns:-")
print(df.shape[1])

Info:-

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Marks       5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

Describe:-

             Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

Number of rows:-

5

Number of columns:-
4

In [115]:
#5. 
# Selecting Name Column

In [116]:
df[["Name"]]

    Name
0   Asha
1   Ravi
2  Meena
3  Kiran
4   Arun

In [117]:
df[["Marks"]]    # marks

   Marks
0     85
1     78
2     92
3     74
4     88

In [118]:
df[["Name", "Marks"]]   # name & marks

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [119]:
#6. Using iloc and loc

In [120]:
print(df.iloc[0])  # First row using iloc

Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object

In [121]:
print(df.iloc[2])    #Third row using iloc

Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object

In [122]:
print(df.iloc[1:4])   #Rows 1 to 3

    Name  Age Department  Marks
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74

In [123]:
#Name and Marks using loc
print(df.loc[:, ["Name", "Marks"]])

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [124]:
#7. Filtering Data

print(df[df["Marks"] > 80])

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88

In [125]:
print(df[(df["Marks"] >= 75) & (df["Marks"] <= 90)])

   Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

In [126]:
print(df[df["Marks"].between(75, 90)])

   Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

In [127]:
print(df[df["Department"] == "CSE"])

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

In [128]:

print(df[(df["Department"] == "CSE") & (df["Marks"] > 80)])

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

In [129]:
# 8. Students belonging to CSE or ECE

print(df[df["Department"].isin(["CSE", "ECE"])])

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
4   Arun   22        ECE     88

In [130]:
#9. Add Result Column

df["Result"] = np.where(df["Marks"] >= 75, "Pass", "Fail")

print(df)

    Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

In [131]:
#10. Add Grade Column
def grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    elif marks >= 70:
        return "C"
    else:
        return "D"

df["Grade"] = df["Marks"].apply(grade)

print(df)

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

In [132]:
#11. Sorting Students

In [133]:
#Marks ascending
print(df.sort_values("Marks"))

print("\n")
#Marks descending
print(df.sort_values("Marks", ascending=False))

    Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A


    Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C

In [134]:
#Department and then Marks
print(df.sort_values(["Department", "Marks"]))

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

In [135]:
#12. Missing Values
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

print("DataFrame:")
print(students)

print("\nMissing values:")
print(students.isnull())

print("\nNumber of missing values in each column:")
print(students.isnull().sum())

print("\nRows containing missing values:")
print(students[students.isnull().any(axis=1)])

DataFrame:
    Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

Missing values:
    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False

Number of missing values in each column:
Name     0
Age      1
Marks    1
dtype: int64

Rows containing missing values:
    Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

In [136]:
#13. Replace Missing Values with Average
students["Age"] = students["Age"].fillna(students["Age"].mean())

students["Marks"] = students["Marks"].fillna(students["Marks"].mean())

print(students)

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

In [137]:
#14. Remove Rows Containing Missing Values

students = students.dropna() # updates the actual dataframe

print(students ,"\n")

#don't want to permanently change the DataFrame then
print(students.dropna())

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

In [138]:
#15. Find and Remove Duplicates

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

print("DataFrame:")
print(df2)

print("\nDuplicate rows:")
print(df2[df2.duplicated()])

print("\nAfter removing duplicates:")
print(df2.drop_duplicates())

DataFrame:
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3   Asha     85
4   Arun     88

Duplicate rows:
   Name  Marks
3  Asha     85

After removing duplicates:
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

In [139]:
#16. Statistical Calculations
marks = pd.DataFrame(
    {
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
    }
)

print("Mean:", marks["Marks"].mean())
print("Median:", marks["Marks"].median())
print("Maximum:", marks["Marks"].max())
print("Minimum:", marks["Marks"].min())
print("Standard deviation:", marks["Marks"].std())
print("Sum:", marks["Marks"].sum())

Mean: 82.0
Median: 85.0
Maximum: 92
Minimum: 67
Standard deviation: 9.82344135219425
Sum: 410

In [140]:
#17. GroupBy — Department Analysis
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],
    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],
    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)

In [141]:
#Average marks by department

print(df.groupby("Department")["Marks"].mean())

Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64

In [142]:
#Maximum marks by department

print(df.groupby("Department")["Marks"].max())

Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64

In [143]:
#Number of students

print(df.groupby("Department")["Name"].count())

Department
CSE    3
ECE    2
ME     1
Name: Name, dtype: int64

In [144]:
df.groupby("Department")["Marks"].agg(["mean", "min", "max", "count"])

                 mean  min  max  count
Department
CSE         85.666667   80   92      3
ECE         83.000000   78   88      2
ME          74.000000   74   74      1

In [145]:
# 2nd way
print(
    df.groupby("Department")["Marks"].agg
    (
        ["mean", "min", "max", "count"]
    )
)

                 mean  min  max  count
Department
CSE         85.666667   80   92      3
ECE         83.000000   78   88      2
ME          74.000000   74   74      1

In [146]:
#18. Combine Two DataFrames Using StudentID

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

result = pd.merge(students, marks, on="StudentID")

print(result)

   StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

In [147]:
#19. Student Performance Analysis

#Create DataFrame
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)
print(df)

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
6   John         ME          72        70          68
7  Priya        ECE          95        91          93

In [148]:
#First five records
print(df.head())

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83

In [149]:
#Dimensions
print(df.shape)

(8, 5)

In [150]:
#Average final mark
print(df["FinalMarks"].mean())

81.625

In [151]:
#Highest-scoring student
print(df.loc[df["FinalMarks"].idxmax()])

Name          Meena
Department      CSE
Attendance       96
Internal         94
FinalMarks       96
Name: 2, dtype: object

In [152]:
#Lowest-scoring student
print(df.loc[df["FinalMarks"].idxmin()])

Name          Kiran
Department       ME
Attendance       68
Internal         65
FinalMarks       62
Name: 3, dtype: object

In [153]:
#Students scoring above 80
print(df[df["FinalMarks"] > 80])

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

In [154]:
#Average marks by department
print(df.groupby("Department")["FinalMarks"].mean())

Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

In [155]:
#Students having attendance above 80%
print(df[df["Attendance"] > 80])

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

In [156]:
#Sort by FinalMarks

print(df.sort_values("FinalMarks", ascending=False))

    Name Department  Attendance  Internal  FinalMarks
2  Meena        CSE          96        94          96
7  Priya        ECE          95        91          93
5  Divya        CSE          88        86          89
0   Asha        CSE          92        85          88
4   Arun        ECE          82        80          83
1   Ravi        ECE          75        72          74
6   John         ME          72        70          68
3  Kiran         ME          68        65          62

In [157]:
#Add Result column
df["Result"] = np.where(
    df["FinalMarks"] >= 70,
    "Pass",
    "Fail"
)

print(df)

    Name Department  Attendance  Internal  FinalMarks Result
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

In [158]:
#Add Performance Category
def performance(marks):
    if marks >= 90:
        return "Excellent"
    elif marks >= 80:
        return "Very Good"
    elif marks >= 70:
        return "Good"
    else:
        return "Needs Improvement"

df["Performance"] = df["FinalMarks"].apply(performance)

print(df)

    Name Department  Attendance  Internal  FinalMarks Result  \
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

         Performance
0          Very Good
1               Good
2          Excellent
3  Needs Improvement
4          Very Good
5          Very Good
6  Needs Improvement
7          Excellent

In [159]:
#Department with highest average FinalMarks
avg_department = df.groupby("Department")["FinalMarks"].mean()

print(avg_department)

print("\nDepartment with highest average:")
print(avg_department.idxmax())

Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

Department with highest average:
CSE

In [160]:
#20. Employee Analysis

#create dataframe

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})

df

,Name,Department,Attendance,Internal,FinalMarks,Result,Performance
0,Asha,CSE,92,85,88,Pass,Very Good
1,Ravi,ECE,75,72,74,Pass,Good
2,Meena,CSE,96,94,96,Pass,Excellent
3,Kiran,ME,68,65,62,Fail,Needs Improvement
4,Arun,ECE,82,80,83,Pass,Very Good
5,Divya,CSE,88,86,89,Pass,Very Good
6,John,ME,72,70,68,Fail,Needs Improvement
7,Priya,ECE,95,91,93,Pass,Excellent

In [161]:
# Average salary
print(employees["Salary"].mean())
print("\n")
#Maximum salary
print(employees["Salary"].max())
print("\n")
#Minimum salary
print(employees["Salary"].min())
print("\n")
#Employee receiving highest salary
print(employees.loc[employees["Salary"].idxmax()])

62875.0


85000


45000


Employee          E06
Department    Finance
Experience          8
Salary          85000
Name: 5, dtype: object

In [162]:
#Employees earning above ₹60,000

print(employees[employees["Salary"] > 60000])

  Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

In [163]:
#Average salary by department
print(employees.groupby("Department")["Salary"].mean())

Department
Finance    73333.333333
HR         50000.000000
IT         61000.000000
Name: Salary, dtype: float64

In [164]:
#Average experience by department

print(employees.groupby("Department")["Experience"].mean())

Department
Finance    5.666667
HR         4.500000
IT         4.666667
Name: Experience, dtype: float64

In [165]:
#Number of employees in each department
print(employees.groupby("Department")["Employee"].count())

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [166]:
#Sort employees by salary
print(employees.sort_values("Salary", ascending=False))

  Employee Department  Experience  Salary
5      E06    Finance           8   85000
2      E03         IT           7   75000
7      E08    Finance           5   70000
3      E04    Finance           4   65000
0      E01         IT           5   60000
4      E05         HR           6   55000
6      E07         IT           2   48000
1      E02         HR           3   45000

In [167]:
#IT employees with more than 3 years experience
print(
    employees[
        (employees["Department"] == "IT") &
        (employees["Experience"] > 3)
    ]
)

  Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000

In [168]:
#Add SalaryLevel column
def salary_level(salary):
    if salary >= 75000:
        return "High"
    elif salary >= 50000:
        return "Medium"
    else:
        return "Low"

employees["SalaryLevel"] = employees["Salary"].apply(salary_level)

print(employees)

  Employee Department  Experience  Salary SalaryLevel
0      E01         IT           5   60000      Medium
1      E02         HR           3   45000         Low
2      E03         IT           7   75000        High
3      E04    Finance           4   65000      Medium
4      E05         HR           6   55000      Medium
5      E06    Finance           8   85000        High
6      E07         IT           2   48000         Low
7      E08    Finance           5   70000      Medium